import { Navigate, useNavigate, useParams } from 'react-router-dom';
import Icon from '../components/Icon';
import NavBar, { BackButton, NavButton } from '../components/NavBar';
import Stub from '../components/Stub';
import { useStory } from '../storage/useStories';

export default function ReadScreen() {
  const { id } = useParams();
  const navigate = useNavigate();
  const story = useStory(id);

  if (!story) return <Navigate to="/library" replace />;

  const words = story.chapters.reduce(
    (sum: number, c) => sum + (c.kind === 'prose' ? c.text.split(/\s+/).length : 0),
    0,
  );

  return (
    <>
      <NavBar
        title="Read"
        left={<BackButton label="Library" onClick={() => navigate('/library')} />}
        right={
          <>
            <NavButton
              label="Achievements"
              onClick={() => navigate(`/story/${story.id}/achievements`)}
            >
              <Icon name="trophy" size={21} />
            </NavButton>
            <NavButton label="Story settings" onClick={() => navigate(`/story/${story.id}/genre`)}>
              <Icon name="book-open" size={21} />
            </NavButton>
          </>
        }
      />
      <div className="screen screen--fixed">
        <Stub milestone="Milestone 4 — paginated reader + page-turn">
          <h2>{story.title || 'Untitled Story'}</h2>
          {story.chapters.length === 0 && (
            <p>
              Nothing written yet. This story was just created, and chapter one is
              generated by the AI client — that lands in milestone 5. Its genre triple
              is <code>{`${story.audience} / ${story.genre} / ${story.setting}`}</code>,
              and it will run to {story.totalChapters} chapters.
            </p>
          )}
          <p>
            {story.chapters.length} chapters stored ({words} words), {story.achievements.length}{' '}
            achievement(s), resume anchor{' '}
            <code>
              chapter {story.readingPosition.chapterIndex} / word {story.readingPosition.wordOffset}
            </code>
            .
          </p>
          <p>
            The real screen measures this text against the live container, breaks it into
            pages, and turns them with a 3D transform. Tap zones: left third back, right
            third forward, centre toggles chrome.
          </p>
          {story.pendingActions.length > 0 && (
            <p>
              <button
                type="button"
                className="nav__btn"
                onClick={() => navigate(`/story/${story.id}/actions`)}
              >
                What happens next? →
              </button>
            </p>
          )}
        </Stub>
      </div>
    </>
  );
}
